### ISSUE TITLE
On add/ Child process exited with non-zero code

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodePackage-https-portal#12]
```
$ curl "http://172.33.0.6:5000/add?from=validator-prysm-pyrmont&to=validator-prysm-pyrmont"
{"error":"Child process exited with non-zero code"}
```

However, the mapping shows up
```
$ curl http://172.33.0.6:5000/dump/txt
validator-prysm-pyrmont.b6fa35f6c459f902.dyndns.dappnode.io -> validator-prysm-pyrmont
```

So maybe the underlying command doesn't API as expected?

**Comment by 3alpha** [comment]
My guess is that problem occurs during reconfiguring of actual https-portal: https://github.com/Shard-Labs/https-portal/blob/master/api/src/app.ts#L44
That should be probably split so error reporting is better. Also, can you check logs and see what's going on there?

**Comment by dapplion** [comment]
> My guess is that problem occurs during reconfiguring of actual https-portal: https://github.com/Shard-Labs/https-portal/blob/master/api/src/app.ts#L44
> That should be probably split so error reporting is better. Also, can you check logs and see what's going on there?

This is all I get in the logs
```
Child process exited with code 1
Child process exited with non-zero code
GET /add?from=sample-from&to=http%3A%2F%2F172.33.0.6%3A5000%2Fdump%2Ftxt 204 51 - 5535.176 ms
```
You may want to print stdout and stderr on error

**Comment by 3alpha** [comment]
I think this is resolved. If need arises, we can reopen issue.
