### ISSUE TITLE
/dump should return subdomain too

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodePackage-https-portal#16]
`/add` endpoint requires to pass a subdomain as arg, but `/dump` return the concatenated domain only. It should return both to ease data validation of the UI. Need to check that a specific subdomain is not used, without guessing what part of the domain is the subdomain.

**Comment by 3alpha** [comment]
I will fix that. Also there is a bug when nothing has been added (or removed) `/dump/txt` fails because file hasn't been generated yet. (This is just reminder for me)
