### ISSUE TITLE
Expose health check at a random route

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodePackage-https-portal#17]
t would be super helpful to expose some health check at a random URL on the NGINX so we know it's alive
Like at /dappnode-health-check return code 200 and ok

This would help a lot debug issues from users

**Comment by 3alpha** [comment]
Also, under this issue I need to research some other way of controlling nginx process. Example:
https://github.com/dappnode/DNP_VPN/blob/f9a8743e59366ec975c461839ea41f5c0097cd27/build/src/src/index.ts#L50

**Comment by 3alpha** [comment]
Opened separate issue for nginx process research, health checks are exposed at `/dappnode-health-check` on both http and https in dbc08313534d6d349c6628528e54027141e126f4
