### ISSUE TITLE
Consider re-writing ruby app in Typescript

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodePackage-https-portal#25]
It's relatively simple and the repo would be more maintainable since DAppNode core devs are fluent in Typescript, not Ruby.

@lukagulin Mentioned the value to keep the package general-purpose, could you detail your point?

**Comment by 3alpha** [comment]
Original HTTPS portal has functionalities that are not in the focus right now, but can be useful for more advanced users. By that I primarily mean that there is already implemented feature which allows https-portal to sign (non wildcard) certificates for any domain. That way, advanced users can set up their DAppNode to use their own domain and certificates are automatically signed. I think that is currently broken now so I have issue opened #18 and fix should be easy to do.

Of course, that is not the critical DAppNode issue so I don't know whether is worth to invest time in it, but it is definitely something that is nice to have (for almost free).

Another thing is that we can loosely follow what is going on on base repo so we can get updates if we wish so.

On the other hand, it would be very nice to have something that everybody can easily understand and that fits so nicely to existing dappnode ecosystem.

Just to note that this issue superseeds #20.

**Comment by 3alpha** [comment]
Done. :)
