### ISSUE TITLE
Start API immediately

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodePackage-https-portal#35]
The current start-up sequence run a setup script first and then the API. The setup script may fail and keep the package in a restarting loop

![Screenshot from 2021-02-08 15-18-01](https://user-images.githubusercontent.com/35266934/107231771-f8c3a080-6a20-11eb-9efc-f856d29ecac2.png)

I propose to start the API right away and do the setup at the same time, and in a way that the API is aware of its status. With this approach users can know the status of the package using the API and not the logs

![Screenshot from 2021-02-08 15-17-32](https://user-images.githubusercontent.com/35266934/107231938-290b3f00-6a21-11eb-9d57-04b056f1ccf8.png)

**Comment by 3alpha** [comment]
Way we do it now was proven to be reliable. Can be reopened if we come across  new issues.
