### ISSUE TITLE
Optimize image size

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodePackage-https-portal#4]
Due to the particularities of DAppNode package distribution over IPFS, it's very important that the docker image size is as low as possible. A rough guide on sizes:
- 50-100 MB: fantastic
- 100-200 MB: good
- over 300 MB: bad

**Comment by dapplion** [comment]
What's the current image size uncompressed?

**Comment by 3alpha** [comment]
It's still in the bad category. Its 358MB But we have problem with big base image of 277MB. This definitely deserves another look so I can reopen issue, but since it was around 700MB I'd say lot of progress was made.
