### ISSUE TITLE
status of DNP_HTTPS

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-https-portal#50]
The recent HTTPS package core integration has generated issues in users' auto-updates. Starting up the HTTPS container may fail due to its port configuration (it uses the frequently used ports 443 and 80), which can be in use by other services. If the HTTPS package startup fails, then the whole update will fail.

Possible solutions:
- Remove HTTPS package from CORE
- Change HTTPS/DAPPMANAGER logic to manually do the port mappings after installation
- Keep HTTPS as core but allow to uninstall it and change core update to skip HTTPS package startup if it fails
- ?

**Comment by dapplion** [comment]
We have removed the HTTPS package from the core + made it stoppable and un-installable
